### ISSUE TITLE
API returning Observable<Void>

### ISSUE THREAD

**Issue by rahulmcs** [JakeWharton/retrofit2-rxjava2-adapter#22]
We are currently upgrading our app to use RxJava 2 and quite a few of our REST API's that return an `Observable<Void>` now fail with the following exception:

```
 Null is not a valid element
java.lang.NullPointerException: Null is not a valid element
                                                                            at io.reactivex.internal.queue.SpscLinkedArrayQueue.offer(SpscLinkedArrayQueue.java:68)
                                                                            at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.onNext(ObservableObserveOn.java:116)
                                                                            at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:63)
                                                                            at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onNext(ObservableOnErrorNext.java:68)
                                                                            at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:51)
                                                                            at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
                                                                            at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:43)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10685)
                                                                            at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10685)
                                                                            at io.reactivex.internal.operators.observable.ObservableOnErrorNext.subscribeActual(ObservableOnErrorNext.java:38)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10685)
                                                                            at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
                                                                            at io.reactivex.Scheduler$1.run(Scheduler.java:134)
                                                                            at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
                                                                            at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                            at java.lang.Thread.run(Thread.java:761)
```

Does this mean that REST Api that do not have a return type should return a `Completable` only?
Otherwise i am looking at major changes to my existing code.

**Comment by JakeWharton** [comment]
Yes. [RxJava 2 does not allow `null` inside of a stream][1]. `Completable` is the appropriate stream type here.

Another more advanced option would be to write a custom `CallAdapter.Factory` which let you define `Observable<NoBody>` using some made up `NoBody` type that had no instances.

 [1]: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#nulls
