### ISSUE TITLE
Flowable.blockingIterable() doesn't propagate Exception

### ISSUE THREAD

**Issue by deandalm** [JakeWharton/retrofit2-rxjava2-adapter#23]
Since upgrading to RxJava2 and using retrofit2-rxjava2-adapter with Retrofit2, we started seeing crashes for ```java.netUnknownHostException``` and ```java.net.SocketException``` in Crashlytics.  After a little investigation, we noticed that any place we used ```Flowable.blockingIterable()``` the exception wasn't propagated so that the try/catch block can handle the Exception.  A simple way to reproduce the issue is to update a resource URL so that it throws a ```com.jakewharton.retrofit2.adapter.rxjava2.HttpException```.

```
FATAL EXCEPTION: pool-7-thread-1
Process: com.silvercar.mobi, PID: 12112
com.jakewharton.retrofit2.adapter.rxjava2.HttpException: HTTP 404 Not Found
        at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
        at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
        at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:43)
        at io.reactivex.Observable.subscribe(Observable.java:10514)
        at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:10514)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:31)
        at io.reactivex.Flowable.subscribe(Flowable.java:12572)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:31)
        at io.reactivex.Flowable.subscribe(Flowable.java:12572)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:156)
        at io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.slowPath(FlowableFromIterable.java:238)
        at io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:123)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onSubscribe(FlowableFlatMap.java:110)
        at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:68)
        at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:46)
        at io.reactivex.Flowable.subscribe(Flowable.java:12572)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:52)
        at io.reactivex.Flowable.subscribe(Flowable.java:12572)
        at io.reactivex.internal.operators.flowable.BlockingFlowableIterable.iterator(BlockingFlowableIterable.java:41)
        at com.silvercar.mobi.data.location.LocationTaskService.onRunTask(LocationTaskService.java:104)
        at com.silvercar.mobi.ui.landing.SplashActivity$1.run(SplashActivity.java:83)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at `java.lang.Thread.run(Thread.java:761)
```

```
final List<LocationAssetResponse> assets = new ArrayList<>();

try {
  Iterable<LocationAssetResponse> iterable = Flowable.fromIterable(response.locations)
    .flatMap(new Function<LocationModel, Publisher<LocationAssetResponse>>() {
      @Override public Publisher<LocationAssetResponse> apply(LocationModel locationModel) throws Exception {
        return service.getAssets(locationModel.id, resolution);
      }
    })
    .blockingIterable();

  for(LocationAssetResponse locationAssetResponse : iterable) {
    assets.add(locationAssetResponse);
  }
} catch(Exception exception) {
  Log.e(getClass().getName(), exception.toString());
}
```

**Comment by JakeWharton** [comment]
This seems like a problem with RxJava 2 and not this library. The exception is provided to `onError`. Can you reproduce the problem just using `Observable.error(new RuntimeException()).blockingIterable()`?

I would file a bug on RxJava directly with regard to this behavior.
